### PR TITLE
Add load_balancing_algorithm_type input variable

### PR DESCRIPTION
**Pull request by linhkikuchi**
## what
* To support other type of load_balancing_algorithm_type (other than the default `round_robin`)

## why
* My use case requires to use `least_outstanding_requests` type

### CODE REVIEW

**Comment by linhkikuchi** [comment]
Can we run test for this PR and get this in?

**Comment by mihaiplesa** [comment]
@jamengual guess it needs a rebase after the year is changed in https://github.com/cloudposse/terraform-aws-alb/pull/128

**Comment by jamengual** [comment]
please run ```make init && make readme```

**Comment by mihaiplesa** [comment]
Looks like all passed.

**Pull request merged**
