### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by maximmi**
## what
- update context.tf to v0.24.1 
- minimum required Terraform version bumped to 0.13.0 
- readme updated, Bridgecrew compliance badges added

## why
- It allows for setting the letter case of tag names and labels, back compatibility with context v0.22.0 and below
- we have dropped support for Terraform 0.12
- To be able see and fix the recommendations from Bridgecrew so we can position our modules as standards compliant

### CODE REVIEW

**Review by Gowiem — DISMISSED** [review]

**Comment by Gowiem** [comment]
@maximmi @osterman anything holding this PR up?

**Review by Nuru — APPROVED** [review]

**Review by Nuru — CHANGES_REQUESTED** [review]
Update all workflows to current versions

**Comment by Nuru** [comment]
Closed in favor of #113

**Pull request closed without merging**
