### PR TITLE
AWS provider V4 compatibility

### PR DESCRIPTION
**Pull request by rstml**
## what
* Replace `cloudposse/lb-s3-bucket` directly with `cloudposse/s3-log-storage`. 
* Use the latest version of `cloudposse/s3-log-storage` for AWS provider V4 compatibility

## why
* Module doesn't work with AWS provider v4
* `cloudposse/lb-s3-bucket` doesn't seem to be maintained and doesn't add much value

## warning
* migration can be destructive. see `cloudposse/s3-log-storage` warnings.

### CODE REVIEW

**Comment by Nuru** [comment]
Thank you for this contribution. We are going to put it on hold for now, since the module works with AWS provider v4.9.0 and the changes here are not backward compatible.

**Comment by rstml** [comment]
The code in this module itself is compatible, but its submodule `cloudposse/lb-s3-bucket` isn't.

Therefore, if one tries to use this module in a code with aws provider >4.0, it fails with the following message:

```
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/alb.access_logs.s3_bucket/main.tf line 30, in resource "aws_s3_bucket" "default":
│   30:         for_each = var.enable_glacier_transition ? [1] : []
│
│ This object does not have an attribute named "enable_glacier_transition".
╵
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/alb.access_logs.s3_bucket/main.tf line 44, in resource "aws_s3_bucket" "default":
│   44:         for_each = var.enable_glacier_transition ? [1] : []
│
│ This object does not have an attribute named "enable_glacier_transition".
╵
```

That happens even if access logging is turned off:

```
module "alb" {
  source  = "cloudposse/alb/aws"
  version = "0.36.0"

  access_logs_enabled               = false
  access_logs_s3_bucket_id          = null
  # ...
```

I believe that's why #110 was also created – this module isn't compatible with v4.

**Comment by Nuru** [comment]
@rstml See #113, which is confirmed to work with AWS v4.9.0

**Comment by rstml** [comment]
Ah, thanks for clarifying. Didn't realise things got better in 4.9.

**Pull request closed without merging**
