### PR TITLE
Removing target group from http_redirect listener rule

### LINKED ISSUE #154: aws_lb_listener.http_redirect Invalid Attribute Combination
### Describe the Bug

In AWS provider 5.35.0 released 2/1/24 if you have a target group arn on a listener with type 'redirect' it will give this error: 

```
│ Warning: Invalid Attribute Combination
│
│   with module.alb.aws_lb_listener.http_redirect[0],
│   on .terraform/modules/alb/main.tf line 183, in resource "aws_lb_listener" "http_redirect":
│  183:     target_group_arn = one(aws_lb_target_group.default[*].arn)
│
│ Attribute "default_action[0].target_group_arn" cannot be specified when "default_action[0].type" is "redirect".
│
│ This will be an error in a future release.
```

### Expected Behavior

No warnings (or future errors) when deploying a redirect listener. 

### Steps to Reproduce

Upgrade to AWS provider 5.35.0 and attempt to deploy an ALB with a redirect listener. 

### Screenshots

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mission-ajennings**
## what

- Removed the target group from being added to http_redirect aws_lb_listener rule. 

## why

- This creates a warning on the latest version of AWS Provider (5.35.0) and will eventually cause an error. 

## references

- [Commit to the provider that causes this warning](https://github.com/hashicorp/terraform-provider-aws/commit/33f49ac3af11137e9773b6f37fda43b58d739cb2)
- closes #154

### CODE REVIEW

**Comment by joe-niland** [comment]
Hi @mission-ajennings 
Thanks for your contribution.

It seems the readme is out of date. Could you please run the following and commit the result?

```
make init
make github/init
make readme
```

**Comment by mission-ajennings** [comment]
> Hi @mission-ajennings Thanks for your contribution.
> 
> It seems the readme is out of date. Could you please run the following and commit the result?
> 
> ```
> make init
> make github/init
> make readme
> ```

thanks @joe-niland new readme pushed

**Comment by joe-niland** [comment]
@mission-ajennings apologies, the template has changed recently.
Would you mind repeating that?

**Comment by osterman** [comment]
@mission-ajennings we're looking into why mergify closed this

**Pull request closed without merging**
