### PR TITLE
feat: alb client keep alive

### PR DESCRIPTION
**Pull request by oycyc**
## what

* Adds the variable and argument for `client_keep_alive`. 
* This was just introduced pretty recently, in May 2024. https://github.com/hashicorp/terraform-provider-aws/issues/36402
  * Therefore updated the version as well, this requires a major bump from v4 to v5.46.0.

## why

image

## references

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#client_keep_alive-1

### CODE REVIEW

**Comment by oycyc** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/36402#issuecomment-2066721726

v5.46.0

**Comment by gberenice** [comment]
@oycyc let's bump the provider version. I'll run the checks+tests and ask the team if there are any objections regarding this major update.

**Comment by oycyc** [comment]
> @oycyc let's bump the provider version. I'll run the checks+tests and ask the team if there are any objections regarding this major update.

Updated, can you run those? Thanks!

**Comment by oycyc** [comment]
Assuming this will require a major bump for the module too now.

**Comment by gberenice** [comment]
Got a 👍 to do the major release (related Slack thread [for the history](https://sweetops.slack.com/archives/G014YEKDH4K/p1731082854909339)).

**Review by gberenice — APPROVED** [review]
Thanks, @oycyc!

**Pull request merged**
