### PR TITLE
update to context

### PR DESCRIPTION
**Pull request by syphernl**
## what
* Update to `context.tf`.

## why
* In `v0.19.0` the `enabled` var was added manually instead of via context.

## references
* Refs #56

### CODE REVIEW

**Comment by syphernl** [comment]
I would really appreciate it if this PR could be tagged with `hacktoberfest-accepted` so it counts towards my [Hacktoberfest](https://hacktoberfest.digitalocean.com/) PR's (since the repo isn't tagged with `hacktoberfest`)

**Comment by joe-niland** [comment]
Hi @syphernl 
Looks good. I think you just need to move your readme updates into the README.yaml file

**Comment by joe-niland** [comment]
@syphernl not sure if you saw my last comment. Also I think we're avoiding using the upper bound on Terraform versions so it should just be ">= 0.12"

**Comment by syphernl** [comment]
> @syphernl disregard previous comment. Was thinking of another project, sorry!

@joe-niland Ah, that explains :) 

> I think we're currently avoiding using the upper bound on Terraform versions so it should just be ">= 0.12"
> 
> I added a PR against your branch for this.

Merged, thanks!

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
@syphernl thanks very much for your contribution. Released!

**Pull request merged**
