### PR TITLE
fix: listener default action variable object block [HOTFIX REQUIRED!]

### PR DESCRIPTION
**Pull request by oycyc**
## what

Removes the default object block and changes it to `null`, making it consistent with the other default actions. The original mindset of having it was to default to HTTP_301 since it's a required attribute, but it doesn't matter because it is not `optional()` in the Terraform. 

## why
As described by @mschfh 
> this adds a redirect by default, as the `default` for the variable is an object, not `null`.
> 
> https://github.com/cloudposse/terraform-aws-alb/blob/cb8fa6558c4f8a49fa3aebf33505397c1ac74ad6/main.tf#L231-L232
> 
> 
> https://github.com/cloudposse/terraform-aws-alb/blob/cb8fa6558c4f8a49fa3aebf33505397c1ac74ad6/variables.tf#L292-L311
> 
> Plan:
> 
> ```
>       ~ default_action {
>           ~ type             = "forward" -> "redirect"
>             # (2 unchanged attributes hidden)
> 
>           + redirect {
>               + host        = "#{host}"
>               + path        = "/#{path}"
>               + port        = "#{port}"
>               + protocol    = "#{protocol}"
>               + query       = "#{query}"
>               + status_code = "HTTP_301"
>             }
>         }
> ```
> 
> Explicitly passing `listener_https_redirect = null` to the module does prevent this change, please update the default or adjust the `for_each`.

image

## references
Comment referencing this issue
https://github.com/cloudposse/terraform-aws-alb/pull/187#issuecomment-2469022563

### CODE REVIEW

**Review by gberenice — APPROVED** [review]
Thanks @oycyc!

**Comment by oycyc** [comment]
Ah looks like the CI failed.
https://github.com/cloudposse/terraform-aws-alb/deployments/release
iScreen Shoter - 20241112075239187

**Comment by oycyc** [comment]
Ugh but the error about README.md.gotmpl never changed within the past 6 months
https://github.com/cloudposse/.github/blob/main/README.md.gotmpl

Do we need someone on the Cloudposse team to look into this?

**Pull request merged**
